"""`vq daemon install`: the daemon's unit gets an owner.

`vq web install` writes and refreshes the console's systemd unit. There was no
equivalent for the daemon, so across the reference fleet its units disagreed:
one referenced `%h/.local/bin/vq`, two hardcoded a pre-split venv path.
Repointing `~/.local/bin/vq` moved the first host and left the other two
running the old vq after a restart, with their config and their symlink both
looking correct. Only `vq doctor`'s `daemon_rpc` version revealed it.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest
from click.testing import CliRunner

from vq import config, paths
from vq.cli import main
from vq.web import install


@pytest.fixture
def host(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    executable = tmp_path / "venv" / "bin" / "vq"
    executable.parent.mkdir(parents=True)
    executable.write_text("#!/bin/sh\n", encoding="utf-8")
    executable.chmod(0o755)
    monkeypatch.setattr(
        install,
        "resolve_service_command",
        lambda kind: [str(executable), *kind.verb],
    )
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "xdg"))
    monkeypatch.setenv(paths.ENV_STATE_DIR, str(tmp_path / "state"))
    monkeypatch.setenv(config.ENV_CONFIG_DIR, str(tmp_path / "config"))
    (tmp_path / "state").mkdir()
    (tmp_path / "config").mkdir()
    return tmp_path


def _unit_path(host: Path) -> Path:
    return host / "xdg" / "systemd" / "user" / "vq-daemon.service"


def _write_unit(host: Path, exec_start: str) -> Path:
    path = _unit_path(host)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "[Unit]\nDescription=vq job queue daemon\n"
        f"[Service]\nExecStart={exec_start}\n",
        encoding="utf-8",
    )
    return path


class TestGeneratedUnit:
    def test_it_points_at_the_vq_that_installed_it(self, host: Path) -> None:
        """Not at `vq` on PATH: a user unit has a different PATH than the
        shell you typed in, which is how two hosts kept a pre-split venv."""
        plan = install.build_plan(
            manager="systemd-user", kind=install.DAEMON_SERVICE,
        )
        unit = plan.writes[0].content

        assert plan.unit_name == "vq-daemon"
        assert f'ExecStart="{host / "venv" / "bin" / "vq"}" "daemon" "run"' in unit
        assert "Description=vq job queue daemon" in unit

    def test_the_unit_carries_no_capacity_caps(self, host: Path) -> None:
        plan = install.build_plan(
            manager="systemd-user", kind=install.DAEMON_SERVICE,
        )
        unit = plan.writes[0].content

        exec_line = next(
            line for line in unit.splitlines() if line.startswith("ExecStart=")
        )
        for flag in install.DAEMON_CAP_FLAGS:
            assert flag not in exec_line

    def test_the_unit_explains_itself_as_a_daemon_unit(self, host: Path) -> None:
        """A console header on a daemon unit misinforms whoever is debugging
        it at 2am."""
        unit = install.build_plan(
            manager="systemd-user", kind=install.DAEMON_SERVICE,
        ).writes[0].content

        assert "generated by `vq daemon install`" in unit
        assert "[daemon]" in unit
        assert "vq web install" not in unit
        assert "[web]" not in unit

    def test_the_console_unit_is_unchanged(self, host: Path) -> None:
        unit = install.build_plan(manager="systemd-user").writes[0].content

        assert "generated by `vq web install`" in unit
        assert '"web" "run"' in unit

    def test_the_two_services_do_not_share_a_marker(self, host: Path) -> None:
        """A marker read as the wrong service would report the wrong owner."""
        console = install.build_plan(manager="systemd-user")
        daemon = install.build_plan(
            manager="systemd-user", kind=install.DAEMON_SERVICE,
        )

        console_marker = console.final_writes[0]
        daemon_marker = daemon.final_writes[0]
        assert console_marker.path != daemon_marker.path
        assert "console_command" in json.loads(console_marker.content)
        assert "daemon_command" in json.loads(daemon_marker.content)


class TestCapsAreNotDroppedSilently:
    """Unit rewrites have repeatedly dropped hardcoded caps in the field."""

    def test_it_refuses_when_the_old_unit_has_caps_the_config_lacks(
        self, host: Path,
    ) -> None:
        _write_unit(
            host,
            "/old/venv/bin/vq daemon run --max-jobs 1 --default-job-mem-mb 8000",
        )
        (host / "config" / "config.toml").write_text(
            'default_host = "localhost"\n', encoding="utf-8",
        )

        result = CliRunner().invoke(
            main,
            ["daemon", "install", "--manager", "systemd-user", "--dry-run"],
        )

        assert result.exit_code != 0
        assert "--max-jobs" in result.output
        assert "--default-job-mem-mb" in result.output
        assert "max_jobs = <value>" in result.output
        assert "default_job_mem_mb = <value>" in result.output
        assert _unit_path(host).read_text().startswith("[Unit]"), (
            "a refusal must not have rewritten the unit"
        )

    def test_a_cap_already_in_the_config_is_not_a_refusal(
        self, host: Path,
    ) -> None:
        """The rewrite preserves it, because the daemon reads it from there."""
        _write_unit(host, "/old/venv/bin/vq daemon run --max-jobs 1")
        (host / "config" / "config.toml").write_text(
            'default_host = "localhost"\n[daemon]\nmax_jobs = 1\n',
            encoding="utf-8",
        )

        result = CliRunner().invoke(
            main,
            ["daemon", "install", "--manager", "systemd-user", "--dry-run"],
        )

        assert result.exit_code == 0, result.output
        assert "dry run" in result.output

    def test_the_refusal_can_be_overridden_deliberately(
        self, host: Path,
    ) -> None:
        _write_unit(host, "/old/venv/bin/vq daemon run --max-jobs 1")
        (host / "config" / "config.toml").write_text(
            'default_host = "localhost"\n', encoding="utf-8",
        )

        result = CliRunner().invoke(
            main,
            [
                "daemon", "install", "--manager", "systemd-user", "--dry-run",
                "--allow-dropping-unit-flags",
            ],
        )

        assert result.exit_code == 0, result.output

    def test_a_unit_with_no_caps_is_replaced_without_ceremony(
        self, host: Path,
    ) -> None:
        _write_unit(host, "%h/.local/bin/vq daemon run")
        (host / "config" / "config.toml").write_text(
            'default_host = "localhost"\n', encoding="utf-8",
        )

        result = CliRunner().invoke(
            main,
            ["daemon", "install", "--manager", "systemd-user", "--dry-run"],
        )

        assert result.exit_code == 0, result.output

    def test_no_existing_unit_is_not_a_refusal(self, host: Path) -> None:
        (host / "config" / "config.toml").write_text(
            'default_host = "localhost"\n', encoding="utf-8",
        )

        result = CliRunner().invoke(
            main,
            ["daemon", "install", "--manager", "systemd-user", "--dry-run"],
        )

        assert result.exit_code == 0, result.output


class TestExecStartFlagReading:
    @pytest.mark.parametrize(
        ("exec_start", "expected"),
        [
            ("/bin/vq daemon run", []),
            ("/bin/vq daemon run --max-jobs 1", ["--max-jobs"]),
            ('"/bin/vq" "daemon" "run" "--max-cpus" "8"', ["--max-cpus"]),
            ("/bin/vq daemon run --max-mem-mb=64000", ["--max-mem-mb"]),
            (
                "/bin/vq daemon run --max-jobs 1 --max-cpus 8",
                ["--max-jobs", "--max-cpus"],
            ),
            ("/bin/vq daemon run --web --web-port 8765", []),
        ],
    )
    def test_it_reads_the_caps_out_of_an_exec_start_line(
        self, host: Path, exec_start: str, expected: list[str],
    ) -> None:
        path = _write_unit(host, exec_start)

        assert install.unit_exec_start_flags(path) == expected

    def test_a_missing_unit_reads_as_no_flags(self, host: Path) -> None:
        assert install.unit_exec_start_flags(_unit_path(host)) == []

    def test_an_executable_path_with_spaces_is_not_split_apart(
        self, host: Path,
    ) -> None:
        """The generated unit quotes every token, and the executable path may
        contain spaces.

        A guard, not a regression test: the earlier strip-the-quotes-then-split
        reader shredded that path into three tokens and still found the flag,
        because flags contain no spaces. This pins the token stream so a future
        reader that looks at argv positionally cannot be quietly wrong.
        """
        path = _write_unit(
            host, '"/venv with spaces/bin/vq" "daemon" "run" "--max-jobs" "1"',
        )

        assert install.unit_exec_start_flags(path) == ["--max-jobs"]

    def test_a_flag_on_a_continuation_line_is_still_found(
        self, host: Path,
    ) -> None:
        """A hand-wrapped ExecStart must not hide a cap.

        This one is a real regression test: the earlier reader raised an
        uncaught `ValueError: No escaped character` on the trailing backslash,
        so `vq daemon install` crashed rather than reporting anything.
        """
        path = _write_unit(
            host,
            "/bin/vq daemon run --max-jobs 1 \\\n"
            "    --default-job-mem-mb 8000",
        )

        assert install.unit_exec_start_flags(path) == [
            "--max-jobs", "--default-job-mem-mb",
        ]

    def test_unbalanced_quotes_still_report_their_flags(
        self, host: Path,
    ) -> None:
        """systemd would reject this unit, but vq must not answer "no caps"
        for a file it could not parse -- that answer drops them silently. The
        whitespace fallback cannot miss a flag.

        A guard: the earlier reader happened to survive this by stripping the
        stray quote first. The fallback is what keeps it true now that quotes
        are honoured.
        """
        path = _write_unit(host, '/bin/vq daemon run --max-cpus "8')

        assert install.unit_exec_start_flags(path) == ["--max-cpus"]


class TestStatusShowsWhoOwnsTheUnit:
    """`vq daemon status` answers "which vq owns this daemon".

    The drift this exists for took a fleet migration to notice: two units
    named a venv path that outlived the vq it pointed at, so repointing the
    symlink moved one host and left the others serving old code after a
    restart, with config and symlink both looking correct.
    """

    def _marker(self, host: Path, **overrides: object) -> None:
        payload = {
            "vq_version": "0.26.0",
            "daemon_command": ["/venv/bin/vq", "daemon", "run"],
            "python": "/venv/bin/python",
            "manager": "systemd-user",
            "unit_name": "vq-daemon",
            "unit_path": str(_unit_path(host)),
            "installed_at": "2026-09-10T00:00:00+00:00",
        }
        payload.update(overrides)
        (host / "config" / install.DAEMON_MARKER_NAME).write_text(
            json.dumps(payload), encoding="utf-8",
        )

    def test_an_uninstalled_unit_points_at_the_verb(self, host: Path) -> None:
        result = CliRunner().invoke(main, ["daemon", "status"])

        assert result.exit_code == 0, result.output
        assert "not installed by vq (`vq daemon install`)" in result.output

    def test_it_names_the_vq_that_installed_the_unit(self, host: Path) -> None:
        from vq import __version__

        self._marker(host, vq_version=__version__)

        result = CliRunner().invoke(main, ["daemon", "status"])

        assert result.exit_code == 0, result.output
        assert f"owner:   vq {__version__}" in result.output
        assert "⚠" not in result.output

    def test_a_unit_from_an_older_vq_is_flagged(self, host: Path) -> None:
        """Exactly the fleet condition: unit pinned to a vq that moved on."""
        self._marker(host, vq_version="0.25.7")

        result = CliRunner().invoke(main, ["daemon", "status"])

        assert result.exit_code == 0, result.output
        assert "unit installed by vq 0.25.7" in result.output
        assert "re-run" in result.output

    def test_the_console_marker_is_not_read_as_the_daemon_s(
        self, host: Path,
    ) -> None:
        """Distinct marker names exist so this cannot report the wrong owner."""
        (host / "config" / install.INSTALL_MARKER_NAME).write_text(
            json.dumps({"vq_version": "0.1.0", "manager": "systemd-user"}),
            encoding="utf-8",
        )

        result = CliRunner().invoke(main, ["daemon", "status"])

        assert result.exit_code == 0, result.output
        assert "not installed by vq" in result.output
        assert "0.1.0" not in result.output

    def test_a_corrupt_marker_does_not_break_the_status(
        self, host: Path,
    ) -> None:
        """Provenance is additive; it must never cost the primary answer."""
        (host / "config" / install.DAEMON_MARKER_NAME).write_text(
            "{ not json", encoding="utf-8",
        )

        result = CliRunner().invoke(main, ["daemon", "status"])

        assert result.exit_code == 0, result.output
        assert "daemon: not running" in result.output


class TestInstallWritesWhatStatusReads:
    """The round trip #10 exists for, with the manager commands stubbed.

    Every other test here uses `--dry-run`, so the unit and the marker were
    only ever described, never written. That leaves the one claim the whole
    verb rests on unchecked: that `vq daemon install` records provenance in
    the place `vq daemon status` looks for it. Distinct marker names and a
    distinct unit name make it easy to write one and read the other.

    Only `subprocess.run` is faked -- systemctl is not available or wanted in
    a test. The files are written for real.
    """

    @pytest.fixture
    def ran(self, monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
        seen: list[list[str]] = []

        def fake_run(argv: list[str], **_: object) -> subprocess.CompletedProcess:
            seen.append(list(argv))
            return subprocess.CompletedProcess(argv, 0, "", "")

        monkeypatch.setattr(install.subprocess, "run", fake_run)
        return seen

    def test_install_then_status_names_this_vq(
        self, host: Path, ran: list[list[str]],
    ) -> None:
        from vq import __version__

        result = CliRunner().invoke(
            main, ["daemon", "install", "--manager", "systemd-user"],
        )
        assert result.exit_code == 0, result.output

        # Written for real, where status looks.
        unit = _unit_path(host)
        assert unit.is_file()
        assert '"daemon" "run"' in unit.read_text()
        assert (host / "config" / install.DAEMON_MARKER_NAME).is_file()

        status = CliRunner().invoke(main, ["daemon", "status"])
        assert status.exit_code == 0, status.output
        assert f"owner:   vq {__version__}" in status.output
        assert str(unit) in status.output

    def test_the_console_is_untouched_by_a_daemon_install(
        self, host: Path, ran: list[list[str]],
    ) -> None:
        """Two services, one installer: neither may write the other's files."""
        result = CliRunner().invoke(
            main, ["daemon", "install", "--manager", "systemd-user"],
        )

        assert result.exit_code == 0, result.output
        assert not (host / "config" / install.INSTALL_MARKER_NAME).exists()
        assert not (
            host / "xdg" / "systemd" / "user" / "vq-web.service"
        ).exists()

    def test_a_failed_manager_command_records_no_provenance(
        self, host: Path, monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """The marker is deferred until every command succeeds, so status
        cannot claim a half-applied service was installed."""
        monkeypatch.setattr(
            install.subprocess,
            "run",
            lambda *a, **k: subprocess.CompletedProcess(
                ["systemctl"], 1, "", "Operation not permitted"
            ),
        )

        result = CliRunner().invoke(
            main, ["daemon", "install", "--manager", "systemd-user"],
        )

        assert result.exit_code != 0
        assert not (host / "config" / install.DAEMON_MARKER_NAME).exists()
        status = CliRunner().invoke(main, ["daemon", "status"])
        assert "not installed by vq" in status.output

    def test_reinstalling_from_a_newer_vq_clears_the_drift(
        self, host: Path, ran: list[list[str]], monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """The remedy `vq daemon status` prints must actually work."""
        from vq import __version__

        (host / "config" / install.DAEMON_MARKER_NAME).write_text(
            json.dumps({
                "vq_version": "0.25.7",
                "manager": "systemd-user",
                "unit_name": "vq-daemon",
                "unit_path": str(_unit_path(host)),
            }),
            encoding="utf-8",
        )
        drifted = CliRunner().invoke(main, ["daemon", "status"])
        assert "unit installed by vq 0.25.7" in drifted.output

        assert CliRunner().invoke(
            main, ["daemon", "install", "--manager", "systemd-user"],
        ).exit_code == 0

        settled = CliRunner().invoke(main, ["daemon", "status"])
        assert f"owner:   vq {__version__}" in settled.output
        assert "0.25.7" not in settled.output
